[package]
name = "portfolio-app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum  = { version = "0.7", default-features = false, optional = true }
console_error_panic_hook = "0.1"
console_log = { version = "1.0", optional = true }
getrandom = { version = "0.2.15", features = ["js"] }
leptos = { version = "0.7", features = ["nightly"] }
leptos_axum = { version = "0.7", default-features = false, features = ["wasm"], optional = true }
leptos_meta = "0.7"
leptos_router = { version = "0.7", features = ["nightly"] }
log = "0.4"
tower-service = "0.3"
wasm-bindgen = "=0.2.99"
wasm-bindgen-futures = "0.4"
worker = { version= "0.5", features = ['http', 'axum', 'd1'], optional = true }

[features]
hydrate = ["dep:console_log", "leptos/hydrate"]
ssr = [ 
  "dep:axum",
  "dep:leptos_axum",
  "dep:worker",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
]

[profile.release]
opt-level = "s"   # optimize for size in release builds
lto = true
strip = true
codegen-units = 1

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle.
output-name = "portfolio_app"

# The site root folder is where cargo-leptos generate all output. 
# WARNING: all content of this folder will be erased on a rebuild.
site-root = "target/site"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
site-pkg-dir = "pkg"

# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
# Env: LEPTOS_ASSETS_DIR.
assets-dir = "public"

# The IP and port where the server serves the content.
site-addr = "127.0.0.1:8787"

# The port to use for automatic reload monitoring
reload-port = 3001

#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"

# Set by cargo-leptos watch when building with that tool. Controls whether autoreload JS will be included in the head
watch = false

# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"

# The features to use when compiling the bin target
# Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
bin-default-features = false

# The features to use when compiling the lib target
# Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
lib-default-features = false