name = "portfolio-app"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-01"

[build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=portfolio_app worker-build --release --features ssr"

[assets]
directory = "./target/site"